# Generated by Django 4.0 on 2021-12-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
